/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ks_livewallpaper_opengl_snowfull_Background */

#ifndef _Included_jp_ks_livewallpaper_opengl_snowfull_Background
#define _Included_jp_ks_livewallpaper_opengl_snowfull_Background
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Background
 * Method:    NDKcreateNativeClass
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Background_NDKcreateNativeClass
  (JNIEnv *, jobject);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Background
 * Method:    NDKinitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Background_NDKinitialize
  (JNIEnv *, jobject);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Background
 * Method:    NDKdraw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Background_NDKdraw
  (JNIEnv *, jobject);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Background
 * Method:    NDKsetOrientation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Background_NDKsetOrientation
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Background
 * Method:    NDKsetPattern
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Background_NDKsetPattern
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Background
 * Method:    NDKsetTextureData
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Background_NDKsetTextureData
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Background
 * Method:    NDKsetMoonVisibility
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Background_NDKsetMoonVisibility
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
