/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer */

#ifndef _Included_jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer
#define _Included_jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer
 * Method:    NDKinitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer_NDKinitialize
  (JNIEnv *, jobject);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer
 * Method:    NDKonSurfaceCreated
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer_NDKonSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer
 * Method:    NDKsetAspect
 * Signature: (IFF)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer_NDKsetAspect
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer
 * Method:    NDKonDrawFrame
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer_NDKonDrawFrame
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer
 * Method:    NDKrelease
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_LiveWallpaperRenderer_NDKrelease
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
