/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ks_livewallpaper_opengl_snowfull_Particle */

#ifndef _Included_jp_ks_livewallpaper_opengl_snowfull_Particle
#define _Included_jp_ks_livewallpaper_opengl_snowfull_Particle
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_ks_livewallpaper_opengl_snowfull_Particle_ORIENTATION_LANDSCAPE
#define jp_ks_livewallpaper_opengl_snowfull_Particle_ORIENTATION_LANDSCAPE 0L
#undef jp_ks_livewallpaper_opengl_snowfull_Particle_ORIENTATION_PORTRAIT
#define jp_ks_livewallpaper_opengl_snowfull_Particle_ORIENTATION_PORTRAIT 1L
/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Particle
 * Method:    NDKcreateNativeClass
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Particle_NDKcreateNativeClass
  (JNIEnv *, jobject);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Particle
 * Method:    NDKinitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Particle_NDKinitialize
  (JNIEnv *, jobject);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Particle
 * Method:    NDKrelease
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Particle_NDKrelease
  (JNIEnv *, jobject);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Particle
 * Method:    NDKsetTextureData
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Particle_NDKsetTextureData
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Particle
 * Method:    NDKdraw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Particle_NDKdraw
  (JNIEnv *, jobject);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Particle
 * Method:    NDKsetParticleNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Particle_NDKsetParticleNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Particle
 * Method:    NDKsetParticleSpeed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Particle_NDKsetParticleSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ks_livewallpaper_opengl_snowfull_Particle
 * Method:    NDKsetOrientation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ks_livewallpaper_opengl_snowfull_Particle_NDKsetOrientation
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
